/**
 * Create each page and add them to the Pages Service.
 * Also set pages in local storage.
 */
function createPages() {
    const pagesService = new PagesService();
    let p = 1;
    
    pagesService.addPage(new Page('Add Your Own Page Numbers', p++));
    pagesService.addPage(new Page('Crack the Spine', p++));
    pagesService.addPage(new Page('Leave this Page Blank on Purpose', p++));
    pagesService.addPage(new Page('Stand Here (wipe your feet, jump up and down) -- 1/2', p++));
    pagesService.addPage(new Page('Stand Here (wipe your feet, jump up and down) -- 2/2', p++));
    pagesService.addPage(new Page('Pour, Spill, Drip, Spit, Fling Your Coffee HERE -- 1/2', p++));
    pagesService.addPage(new Page('Pour, Spill, Drip, Spit, Fling Your Coffee HERE -- 2/2', p++));
    pagesService.addPage(new Page('Poke Holes in this Page Using a Pencil -- 1/2', p++));
    pagesService.addPage(new Page('Poke Holes in this Page Using a Pencil -- 2/2', p++));
    pagesService.addPage(new Page('Draw Fat Lines and Thin, Pushing Really Hard with the Pencil. -- 1/2', p++));
    pagesService.addPage(new Page('Draw Fat Lines and Thin, Pushing Really Hard with the Pencil. -- 2/2', p++));
    pagesService.addPage(new Page('This Page is for HANDPRINTS or Fingerprints. Get Them Dirty then Press Down -- 1/2', p++));
    pagesService.addPage(new Page('This Page is for HANDPRINTS or Fingerprints. Get Them Dirty then Press Down -- 2/2', p++));
    pagesService.addPage(new Page('Color this Entire Page -- 1/2', p++));
    pagesService.addPage(new Page('Color this Entire Page -- 2/2', p++));
    pagesService.addPage(new Page('Throw Something. A Pencil, a Ball Dipped in Paint -- 1/2', p++));
    pagesService.addPage(new Page('Throw Something. A Pencil, a Ball Dipped in Paint -- 2/2', p++));
    pagesService.addPage(new Page('Press Leaves and Other Found Things -- 1/2', p++));
    pagesService.addPage(new Page('Press Leaves and Other Found Things -- 2/2', p++));
    pagesService.addPage(new Page('Scratch Using a Sharp Object -- 1/2', p++));
    pagesService.addPage(new Page('Scratch Using a Sharp Object -- 2/2', p++));
    pagesService.addPage(new Page('Do Some Rubbings with a Pencil -- 1/2', p++));
    pagesService.addPage(new Page('Do Some Rubbings with a Pencil -- 2/2', p++));
    pagesService.addPage(new Page('Scribble Wildly, Violently, with Reckless Abandon -- 1/2', p++));
    pagesService.addPage(new Page('Scribble Wildly, Violently, with Reckless Abandon -- 2/2', p++));
    pagesService.addPage(new Page('Tear Strips, Rip it Up! -- 1/2', p++));
    pagesService.addPage(new Page('Tear Strips, Rip it Up! -- 2/2', p++));
    pagesService.addPage(new Page('Glue, Staple, or Tape these Pages Together -- 1/2', p++));
    pagesService.addPage(new Page('Glue, Staple, or Tape these Pages Together -- 2/2', p++));
    pagesService.addPage(new Page('Draw Lines While in Motion. On the Bus, on the Train, While Walking -- 1/2', p++));
    pagesService.addPage(new Page('Draw Lines While in Motion. On the Bus, on the Train, While Walking -- 2/2', p++));
    pagesService.addPage(new Page('Fill this Page with Circles -- 1/2', p++));
    pagesService.addPage(new Page('Fill this Page with Circles -- 2/2', p++));
    pagesService.addPage(new Page('Document Your Dinner -- 1/2', p++));
    pagesService.addPage(new Page('Document Your Dinner -- 2/2', p++));
    pagesService.addPage(new Page('Chew on This *Warning: Do Not Swallow -- 1/2', p++));
    pagesService.addPage(new Page('Chew on This *Warning: Do Not Swallow -- 2/2', p++));
    pagesService.addPage(new Page('Make a Funnel. Drink Some Water -- 1/2', p++));
    pagesService.addPage(new Page('Make a Funnel. Drink Some Water -- 2/2', p++));
    pagesService.addPage(new Page('Tear Out. Crumple -- 1/2', p++));
    pagesService.addPage(new Page('Tear Out. Crumple -- 2/2', p++));
    pagesService.addPage(new Page('Make a Paper Airplane -- 1/2', p++));
    pagesService.addPage(new Page('Make a Paper Airplane -- 2/2', p++));
    pagesService.addPage(new Page('Wrap Something with this Page -- 1/3', p++));
    pagesService.addPage(new Page('Wrap Something with this Page -- 2/3', p++));
    pagesService.addPage(new Page('Wrap Something with this Page -- 3/3', p++));
    pagesService.addPage(new Page('Tounge Painting. 1. Eat Some Colorful Candy. 2. Lick this Page.  -- 1/2', p++));
    pagesService.addPage(new Page('Write One Word Over and Over  -- 1/2', p++));
    pagesService.addPage(new Page('Write One Word Over and Over -- 2/2', p++));
    pagesService.addPage(new Page('Tie a String to the Spine of this Book. Swing Wildly. Let it Hit the Walls. -- 1/2', p++));
    pagesService.addPage(new Page('Tie a String to the Spine of this Book. Swing Wildly. Let it Hit the Walls. -- 2/2', p++));
    pagesService.addPage(new Page('Pick Up the Journal without Using your Hands -- 1/2', p++));
    pagesService.addPage(new Page('Pick Up the Journal without Using your Hands -- 2/2', p++));
    pagesService.addPage(new Page('Climb Up High. Drop the Journal -- 1/2', p++));
    pagesService.addPage(new Page('Climb Up High. Drop the Journal -- 2/2', p++));
    pagesService.addPage(new Page('Compost this Page. Watch it Deteriorate -- 1/2', p++));
    pagesService.addPage(new Page('Compost this Page. Watch it Deteriorate -- 2/2', p++));
    pagesService.addPage(new Page('Do a Really Ugly Drawing -- 1/2', p++));
    pagesService.addPage(new Page('Do a Really Ugly Drawing -- 2/2', p++));
    pagesService.addPage(new Page('Place Sticky Things Here -- 1/2', p++));
    pagesService.addPage(new Page('Place Sticky Things Here -- 2/2', p++));
    pagesService.addPage(new Page('Pretend You are Doodling on the Back of an Envelope While on the Phone -- 1/2', p++));
    pagesService.addPage(new Page('Pretend You are Doodling on the Back of an Envelope While on the Phone -- 2/2', p++));
    pagesService.addPage(new Page('Journal Golf -- 1/3', p++));
    pagesService.addPage(new Page('Journal Golf -- 2/3', p++));
    pagesService.addPage(new Page('Journal Golf -- 3/3', p++));
    pagesService.addPage(new Page('Make a Paper Chain -- 1/2', p++));
    pagesService.addPage(new Page('Make a Paper Chain -- 2/2', p++));
    pagesService.addPage(new Page('Collect Fruit Stickers Here', p++));
    pagesService.addPage(new Page('Cover this Page Using Only Office Supplies -- 1/2', p++));
    pagesService.addPage(new Page('Cover this Page Using Only Office Supplies -- 2/2', p++));
    pagesService.addPage(new Page('Bring this Book in the Shower with You -- 1/2', p++));
    pagesService.addPage(new Page('Bring this Book in the Shower with You -- 2/2', p++));
    pagesService.addPage(new Page('Tie a String to the Journal. Go for a Walk, Drag it -- 1/2', p++));
    pagesService.addPage(new Page('Tie a String to the Journal. Go for a Walk, Drag it -- 2/2', p++));
    pagesService.addPage(new Page('Rub Here with Dirt -- 1/2', p++));
    pagesService.addPage(new Page('Rub Here with Dirt -- 2/2', p++));
    pagesService.addPage(new Page('Use this as a Test Page -- 1/2', p++));
    pagesService.addPage(new Page('Use this as a Test Page -- 2/2', p++));
    pagesService.addPage(new Page('Drip Something Here. (ink, paint, tea) Close the Book to Make a Print -- 1/2', p++));
    pagesService.addPage(new Page('Drip Something Here. (ink, paint, tea) Close the Book to Make a Print -- 2/2', p++));
    pagesService.addPage(new Page('Sew this Page -- 1/2', p++));
    pagesService.addPage(new Page('Sew this Page -- 2/2', p++));
    pagesService.addPage(new Page('Glue a Random Page from a Newspaper Here -- 1/2', p++));
    pagesService.addPage(new Page('Glue a Random Page from a Newspaper Here -- 2/2', p++));
    pagesService.addPage(new Page('A Place for your Grocery Lists -- 1/2', p++));
    pagesService.addPage(new Page('A Place for your Grocery Lists -- 2/2', p++));
    pagesService.addPage(new Page('Collect the Stamps Off All your Mail -- 1/2', p++));
    pagesService.addPage(new Page('Collect the Stamps Off All your Mail -- 2/2', p++));
    pagesService.addPage(new Page('Trace the Things in your Bag (or Pockets). Let the Lines Overlap -- 1/2', p++));
    pagesService.addPage(new Page('Trace the Things in your Bag (or Pockets). Let the Lines Overlap -- 2/2', p++));
    pagesService.addPage(new Page('Cover this Page with White Things -- 1/2', p++));
    pagesService.addPage(new Page('Cover this Page with White Things -- 2/2', p++));
    pagesService.addPage(new Page('Scribble Wildly Using Only Borrowed Pens. (document where they were borrowed from.) -- 1/2', p++));
    pagesService.addPage(new Page('Scribble Wildly Using Only Borrowed Pens. (document where they were borrowed from.) -- 2/2', p++));
    pagesService.addPage(new Page('Make a Sudden, Destructive, Unpredictable Movement with the Journal -- 1/2', p++));
    pagesService.addPage(new Page('Make a Sudden, Destructive, Unpredictable Movement with the Journal -- 2/2', p++));
    pagesService.addPage(new Page('Make a Mess. Clean it Up -- 1/2', p++));
    pagesService.addPage(new Page('Make a Mess. Clean it Up -- 2/2', p++));
    pagesService.addPage(new Page('Doodle Over Top of: the Cover. the Title Page. the Instructions. the Copyright Page. Fold Down the Corners of your Favorite Pages -- 1/2', p++));
    pagesService.addPage(new Page('Doodle Over Top of: the Cover. the Title Page. the Instructions. the Copyright Page. Fold Down the Corners of your Favorite Pages -- 2/2', p++));
    pagesService.addPage(new Page('Page of Good Thoughts -- 1/2', p++));
    pagesService.addPage(new Page('Page of Good Thoughts -- 2/2', p++));
    pagesService.addPage(new Page('Make Prints Using an Ink Pad and Cut Vegetables -- 1/2', p++));
    pagesService.addPage(new Page('Make Prints Using an Ink Pad and Cut Vegetables -- 2/2', p++));
    pagesService.addPage(new Page('Ask a Friend to Do Something Destructive to this Page. Don\'t look -- 1/2', p++));
    pagesService.addPage(new Page('Ask a Friend to Do Something Destructive to this Page. Don\'t look -- 1/2', p++));
    pagesService.addPage(new Page('Write Carelessly Now -- 1/2', p++));
    pagesService.addPage(new Page('Write Carelessly Now -- 2/2', p++));
    pagesService.addPage(new Page('Glue Random Things Here -- 1/2', p++));
    pagesService.addPage(new Page('Glue Random Things Here -- 2/2', p++));
    pagesService.addPage(new Page('Tear this Page Out. Put it in your Pocket. Put it Through the Wash. Stick it Back in -- 1/3', p++));
    pagesService.addPage(new Page('Tear this Page Out. Put it in your Pocket. Put it Through the Wash. Stick it Back in -- 2/3', p++));
    pagesService.addPage(new Page('Tear this Page Out. Put it in your Pocket. Put it Through the Wash. Stick it Back in -- 3/3', p++));
    pagesService.addPage(new Page('Cut Through Several Layers', p++));
    pagesService.addPage(new Page('Infuse this Page with a Smell of your Choosing -- 1/2', p++));
    pagesService.addPage(new Page('Infuse this Page with a Smell of your Choosing -- 2/2', p++));
    pagesService.addPage(new Page('Color Outside of the Lines -- 1/2', p++));
    pagesService.addPage(new Page('Color Outside of the Lines -- 2/2', p++));
    pagesService.addPage(new Page('Close your Eyes. Connect the Dots from Memory -- 1/2', p++));
    pagesService.addPage(new Page('Close your Eyes. Connect the Dots from Memory -- 2/2', p++));
    pagesService.addPage(new Page('Hang the Journal in a Public Place. Invite People to Draw Here -- 1/2', p++));
    pagesService.addPage(new Page('Hang the Journal in a Public Place. Invite People to Draw Here -- 2/2', p++));
    pagesService.addPage(new Page('Collect your Pocket Lint. Glue it Here -- 1/2', p++));
    pagesService.addPage(new Page('Collect yoru Pocket Lint. Glue it Here -- 2/2', p++));
    pagesService.addPage(new Page('Trace your Hand -- 1/2', p++));
    pagesService.addPage(new Page('Trace your Hand -- 2/2', p++));
    pagesService.addPage(new Page('Draw with Glue -- 1/2', p++));
    pagesService.addPage(new Page('Draw with Glue -- 2/2', p++));
    pagesService.addPage(new Page('Sample Various Substances Found in your Home. Document what they are. Create Color Themes -- 1/2', p++));
    pagesService.addPage(new Page('Sample Various Substances Found in your Home. Document what they are. Create Color Themes -- 2/2', p++));
    pagesService.addPage(new Page('Document a Boring Event in Detail -- 1/2', p++));
    pagesService.addPage(new Page('Document a Boring Event in Detail -- 2/2', p++));
    pagesService.addPage(new Page('Create a Drawing Using a Piece (or several pieces) of your Hair -- 1/2', p++));
    pagesService.addPage(new Page('Create a Drawing Using a Piece (or several pieces) of your Hair -- 2/2', p++));
    pagesService.addPage(new Page('Glue in a Photo of Yourself you Dislike. DEFACE -- 1/2', p++));
    pagesService.addPage(new Page('Glue in a Photo of Yourself you Dislike. DEFACE -- 2/2', p++));
    pagesService.addPage(new Page('Draw Lines Using Abnormal Writing Utensils Dipped in Ink or Paint (sticks, spoons, twist ties, comb, etc.) -- 1/2', p++));
    pagesService.addPage(new Page('Draw Lines Using Abnormal Writing Utensils Dipped in Ink or Paint (sticks, spoons, twist ties, comb, etc.) -- 2/2', p++));
    pagesService.addPage(new Page('Fill in this Page when you are Really ANGRY -- 1/2', p++));
    pagesService.addPage(new Page('Fill in this Page when you are Really ANGRY -- 2/2', p++));
    pagesService.addPage(new Page('Write or Draw with your Left Hand -- 1/2', p++));
    pagesService.addPage(new Page('Write or Draw with your Left Hand -- 2/2', p++));
    pagesService.addPage(new Page('Find a Way to Wear the Journal -- 1/2', p++));
    pagesService.addPage(new Page('Find a Way to Wear the Journal -- 2/2', p++));
    pagesService.addPage(new Page('This Page is a Sign. What do you Want it to Say? -- 1/2', p++));
    pagesService.addPage(new Page('This Page is a Sign. What do you Want it to Say? -- 2/2', p++));
    pagesService.addPage(new Page('Create a Nonstop Line -- 1/2', p++));
    pagesService.addPage(new Page('Create a Nonstop Line -- 2/2', p++));
    pagesService.addPage(new Page('Space for Negative Comments -- 1/2', p++));
    pagesService.addPage(new Page('Space for Negative Comments -- 2/2', p++));
    pagesService.addPage(new Page('Draw Lines with your Pen or Pencil. Lick your Finger and Smear the Lines -- 1/2', p++));
    pagesService.addPage(new Page('Draw Lines with your Pen or Pencil. Lick your Finger and Smear the Lines -- 2/2', p++));
    pagesService.addPage(new Page('Lose this Page. (throw it out.) Accept the Loss -- 1/3', p++));
    pagesService.addPage(new Page('Lose this Page. (throw it out.) Accept the Loss -- 2/3', p++));
    pagesService.addPage(new Page('Lose this Page. (throw it out.) Accept the Loss -- 3/3', p++));
    pagesService.addPage(new Page('Page for Four-Letter Words', p++));
    pagesService.addPage(new Page('Glue in a Page from a Magazine. Circle Words you Like -- 1/2', p++));
    pagesService.addPage(new Page('Glue in a Page from a Magazine. Circle Words you Like -- 2/2', p++));
    pagesService.addPage(new Page('Write with the Pen in your Mouth -- 1/2', p++));
    pagesService.addPage(new Page('Write with the Pen in your Mouth -- 2/2', p++));
    pagesService.addPage(new Page('Give Away your Favorite Page -- 1/2', p++));
    pagesService.addPage(new Page('Give Away your Favorite Page -- 2/2', p++));
    pagesService.addPage(new Page('.drawkcab etirW -- 1/2', p++));
    pagesService.addPage(new Page('.drawkcab etirW -- 2/2', p++));
    pagesService.addPage(new Page('Document Time Passing -- 1/2', p++));
    pagesService.addPage(new Page('Document Time Passing -- 2/2', p++));
    pagesService.addPage(new Page('This Space is Dedicated to Internal Monologue -- 1/2', p++));
    pagesService.addPage(new Page('This Space is Dedicated to Internal Monologue -- 2/2', p++));
    pagesService.addPage(new Page('Scrub this Page -- 1/2', p++));
    pagesService.addPage(new Page('Scrub this Page -- 2/2', p++));
    pagesService.addPage(new Page('Hide a Secret Message Somewhere in this Book -- 1/2', p++));
    pagesService.addPage(new Page('Hide a Secret Message Somewhere in this Book -- 2/2', p++));
    pagesService.addPage(new Page('Sleep with the Journal. Describe the Experience Here -- 1/2', p++));
    pagesService.addPage(new Page('Sleep with the Journal. Describe the Experience Here -- 2/2', p++));
    pagesService.addPage(new Page('Close the Journal. Write/Scribble Something on the Edges -- 1/2', p++));
    pagesService.addPage(new Page('Close the Journal. Write/Scribble Something on the Edges -- 2/2', p++));
    pagesService.addPage(new Page('Write a List of More Ways to Wreck this Journal -- 1/2', p++));
    pagesService.addPage(new Page('Write a List of More Ways to Wreck this Journal -- 2/2', p++));
    pagesService.addPage(new Page('Stain Log -- 1/2', p++));
    pagesService.addPage(new Page('Stain Log -- 2/2', p++));
    pagesService.addPage(new Page('Doodle Over Top of this Page and in the Margins -- 1/2', p++));
    pagesService.addPage(new Page('Doodle Over Top of this Page and in the Margins -- 2/2', p++));
    pagesService.addPage(new Page('Figure Out a Way to Attach these Two Pages Together -- 1/2', p++));
    pagesService.addPage(new Page('Figure Out a Way to Attach these Two Pages Together -- 2/2', p++));
    pagesService.addPage(new Page('Rub this Page on a Dirty Surface -- 1/2', p++));
    pagesService.addPage(new Page('Rub this Page on a Dirty Surface -- 2/2', p++));
    pagesService.addPage(new Page('Collect the Letter "W" Here -- 1/2', p++));
    pagesService.addPage(new Page('Collect the Letter "W" Here -- 2/2', p++));
    pagesService.addPage(new Page('Collect Dead Bugs Here -- 1/2', p++));
    pagesService.addPage(new Page('Collect Dead Bugs Here -- 2/2', p++));
    pagesService.addPage(new Page('Drum on this Page with Pencils -- 1/2', p++));
    pagesService.addPage(new Page('Drum on this Page with Pencils -- 2/2', p++));
    pagesService.addPage(new Page('Float this Page -- 1/2', p++));
    pagesService.addPage(new Page('Float this Page -- 2/2', p++));
    pagesService.addPage(new Page('Figure Out a Way to Freeze this Page -- 1/2', p++));
    pagesService.addPage(new Page('Figure Out a Way to Freeze this Page -- 2/2', p++));
    pagesService.addPage(new Page('Hide this Page in your Neighbor\'s Yard -- 1/2', p++));
    pagesService.addPage(new Page('Hide this Page in your Neighbor\'s Yard -- 2/2', p++));
    pagesService.addPage(new Page('Roll the Journal Down a Large Hill -- 1/2', p++));
    pagesService.addPage(new Page('Roll the Journal Down a Large Hill -- 2/2', p++));
    pagesService.addPage(new Page('Sell this Page -- 1/2', p++));
    pagesService.addPage(new Page('Sell this Page -- 2/2', p++));
    pagesService.addPage(new Page('Turn the Book into a Shoe -- 1/2', p++));
    pagesService.addPage(new Page('Turn the Book into a Shoe -- 2/2', p++));
    pagesService.addPage(new Page('Slide the Journal (this page face-down), Down a Long Hallway -- 1/2', p++));
    pagesService.addPage(new Page('Slide the Journal (this page face-down), Down a Long Hallway -- 2/2', p++));
    pagesService.addPage(new Page('Smush Something Colorful Onto this Page -- 1/2', p++));
    pagesService.addPage(new Page('Smush Somethign Colorful Onto this Page -- 2/2', p++));
    pagesService.addPage(new Page('Squirt Liquid Here (try using your mouth) -- 1/2', p++));
    pagesService.addPage(new Page('Squirt Liquid Here (try using your mouth) -- 2/2', p++));
    pagesService.addPage(new Page('Cover this Page in Tape (create some kind of pattern) -- 1/2', p++));
    pagesService.addPage(new Page('Cover this Page in Tape (create some kind of pattern) -- 2/2', p++));
    pagesService.addPage(new Page('Trace your Toes -- 1/2', p++));
    pagesService.addPage(new Page('Trace your Toes -- 2/2', p++));
    pagesService.addPage(new Page('Tape this Journal Closed and Mail it to Yourself', p++));

    localStorage.setItem('pages', JSON.stringify([...pagesService.getPages()]));
}